wipContainerRegistry:
  name: eminence
  fqdn: eminence.azurecr.io
officialContainerRegistry:
  name: tyger
  fqdn: tyger.azurecr.io
keyVault: eminence
testAppUri: api://tyger-test-client
pemCertSecret:
  name: tyger-test-client-cert
  version: 0fe705f5a0f94771bd38f7e997540497
pkcs12CertSecret:
  name: tyger-test-client-cert-pkcs12
  version: f8b1b7dde7034217bf12ce4ea772b470
localBufferServiceCertSecret:
  name: tyger-local-buffer-service-cert
  version: 3a2b9983673442bfb51f8bb4958972f8
