subscriptionId: 87d8acb3-5176-4651-b457-6ab9cefd8e3d
wipContainerRegistry:
  fqdn: eminence.azurecr.io
officialPushContainerRegistry:
  fqdn: tygerprod.azurecr.io
  directory: /public/tyger
officialPullContainerRegistry:
  fqdn: mcr.microsoft.com
  directory: /tyger
keyVault: eminence
pemCertSecret:
  name: tyger-test-client-cert
  version: b663cfaf65b245879304c0419960e0f3
pkcs12CertSecret:
  name: tyger-test-client-cert-pkcs12
  version: b4382870a79841119c9e27851302412c
