name: tyger
channels:
  - ismrmrd
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.6.0
  - bash-completion=2.11
  - dotnet=7.0.100
  - dvc-azure=2.21.0
  - h5py=3.2.1
  - hdf5=1.10.6
  - ismrmrd=1.13.1
  - ismrmrd-python=1.13.1
  - jupyter=1.0.0
  - kubernetes-client=1.24.3
  - kubernetes-helm=3.10.2
  - make=4.3
  - matplotlib=3.4.3
  - numpy=1.22.0
  - pugixml=1.11.4
  - pylint=2.11.1
  - pytest=6.2.5
  - pytest-xdist=3.2.1
  - python=3.9.7
  - shellcheck=0.7.2
  - siemens_to_ismrmrd=1.2.8
