job:
  codespec:
    image: eminencepublic.azurecr.io/gadgetron:current
    buffers:
      inputs:
        - input
      outputs:
        - output
    args:
      - "-c"
      - "default.xml"
      - "--from_stream"
      - "-i"
      - "$(INPUT_PIPE)"
      - "-o"
      - "$(OUTPUT_PIPE)"
    resources:
      requests:
        cpu: 1
        memory: 1G
      limits:
        memory: 1G
